# Generated by Django 3.2.9 on 2021-11-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20211117_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='name',
            field=models.CharField(default='Board', max_length=200),
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='Category', max_length=200),
        ),
    ]
