# Generated by Django 3.2.9 on 2021-11-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20211117_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tasks.board'),
        ),
    ]
