# Generated by Django 3.2.9 on 2021-11-21 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_category_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.CharField(default=None, max_length=500),
            preserve_default=False,
        ),
    ]
