# Generated by Django 3.2.9 on 2021-11-23 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_board_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
