# Generated by Django 3.2.9 on 2021-11-24 20:52
# Generated by Django 3.2.9 on 2021-11-24 23:30


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_task_status'),
        ('tasks', '0016_auto_20211123_2259'),
    ]

    operations = [
    ]
