# Generated by Django 3.2.9 on 2021-11-25 04:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_friendrequest'),
        ('tasks', '0017_merge_0015_task_status_0016_auto_20211123_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='assigned',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.myuser'),
        ),
    ]
