# Generated by Django 3.2.9 on 2021-11-22 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_board_owner'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='boardsToCollaborate',
        ),
        migrations.AddField(
            model_name='myuser',
            name='boardsToCollaborate',
            field=models.ManyToManyField(null=True, related_name='team', to='tasks.Board'),
        ),
    ]
