# Generated by Django 3.2.9 on 2021-11-23 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_myuser_boardstocollaborate'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='friends',
            field=models.ManyToManyField(blank=True, to='user.MyUser'),
        ),
    ]
